# Generated by Django 2.2.1 on 2019-05-24 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('biography', models.CharField(default='Biography coming soon!', max_length=5000)),
                ('image', models.ImageField(upload_to='chair_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Commtype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Only alphanumeric, dashes, and underscores allowed', regex='^[a-zA-Z0-9_\\-]+$')])),
            ],
        ),
        migrations.CreateModel(
            name='Techmuncommittee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Only alphanumeric, dashes, and underscores allowed', regex='^[a-zA-Z0-9_\\-]+$')])),
                ('is_crisis', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='techmun_photos/')),
                ('chairs', models.ManyToManyField(limit_choices_to=3, related_name='committee', to='techmun.Chair')),
            ],
        ),
        migrations.RemoveField(
            model_name='committee',
            name='delegations',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='committees',
        ),
        migrations.DeleteModel(
            name='Delegation',
        ),
        migrations.RemoveField(
            model_name='year',
            name='conferences',
        ),
        migrations.DeleteModel(
            name='Committee',
        ),
        migrations.DeleteModel(
            name='Conference',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
        migrations.AddField(
            model_name='commtype',
            name='committees',
            field=models.ManyToManyField(related_name='commtype', to='techmun.Techmuncommittee'),
        ),
    ]
