# Generated by Django 2.2.1 on 2019-06-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmun', '0002_auto_20190524_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='chair',
            name='is_director',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='techmuncommittee',
            name='background_guide',
            field=models.FileField(blank=True, null=True, upload_to='background_guides/'),
        ),
        migrations.AddField(
            model_name='techmuncommittee',
            name='topic1',
            field=models.CharField(default='Topic 1 coming soon!', max_length=100),
        ),
        migrations.AddField(
            model_name='techmuncommittee',
            name='topic2',
            field=models.CharField(default='Topic 2 coming soon!', max_length=100),
        ),
        migrations.AlterField(
            model_name='techmuncommittee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='techmun_photos/'),
        ),
    ]
