# Generated by Django 2.2.1 on 2019-06-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmun', '0005_auto_20190620_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techmuncommittee',
            name='chairs',
            field=models.ManyToManyField(related_name='committee', to='techmun.Chair'),
        ),
    ]
