# Generated by Django 2.2.1 on 2019-06-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmun', '0006_auto_20190620_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chair',
            name='biography',
            field=models.TextField(default='Biography coming soon!', max_length=5000),
        ),
    ]
