# Generated by Django 2.2.2 on 2019-06-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmun', '0007_auto_20190621_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='commtype',
            name='rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='techmuncommittee',
            name='is_middleschool',
            field=models.BooleanField(default=False),
        ),
    ]
