# Generated by Django 2.2.2 on 2019-06-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmun', '0008_auto_20190625_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='techmuncommittee',
            name='style',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
