# Generated by Django 2.2.3 on 2020-01-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmun', '0009_techmuncommittee_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techmuncommittee',
            name='chairs',
            field=models.ManyToManyField(blank=True, null=True, related_name='committee', to='techmun.Chair'),
        ),
    ]
