# Generated by Django 2.2.1 on 2019-05-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='delegationaward',
            field=models.CharField(max_length=200),
        ),
    ]
