# Generated by Django 2.2.1 on 2019-06-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_auto_20190524_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='award_photos/'),
        ),
    ]
