# Generated by Django 2.2.2 on 2019-06-28 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_conference_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegation',
            name='award',
        ),
    ]
