# Generated by Django 2.2.2 on 2019-06-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_remove_delegation_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='delegationaward',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
