# Generated by Django 2.2.2 on 2019-06-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_auto_20190628_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
