# Generated by Django 2.2.3 on 2019-07-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0006_auto_20190628_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='year_photos/'),
        ),
    ]
