# Generated by Django 2.2.2 on 2019-06-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ecc',
            field=models.FileField(null=True, upload_to='ecc_forms/'),
        ),
        migrations.AddField(
            model_name='user',
            name='health',
            field=models.FileField(null=True, upload_to='health_forms/'),
        ),
    ]
