# Generated by Django 2.2.3 on 2019-10-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_driver_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_ride',
            field=models.FileField(null=True, upload_to='mcmunc_rider/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='driver_form',
            field=models.FileField(null=True, upload_to='mcmunc_driver/'),
        ),
    ]
