# Generated by Django 2.2.3 on 2019-10-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191009_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='driver_form',
            field=models.FileField(blank=True, null=True, upload_to='mcmunc_driver/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_ride',
            field=models.FileField(blank=True, null=True, upload_to='mcmunc_rider/'),
        ),
    ]
