# Generated by Django 2.2.3 on 2019-10-13 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_next_conf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='next_conf',
        ),
        migrations.CreateModel(
            name='Next_Conf',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('dels', models.ManyToManyField(related_name='current_dels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
