# Generated by Django 2.2.3 on 2019-10-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191013_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='driver_form',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_ride',
        ),
        migrations.AddField(
            model_name='user',
            name='code_of_conduct',
            field=models.FileField(default=None, null=True, upload_to='wmhsmun_conduct/'),
        ),
        migrations.AddField(
            model_name='user',
            name='delegate_release',
            field=models.FileField(default=None, null=True, upload_to='wmhsmun_delrelease/'),
        ),
        migrations.AddField(
            model_name='user',
            name='luggage_search',
            field=models.FileField(default=None, null=True, upload_to='wmhsmun_luggage/'),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_auth',
            field=models.FileField(default=None, null=True, upload_to='wmhsmun_parent/'),
        ),
    ]
