# Generated by Django 2.2.3 on 2019-10-30 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20191029_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='parent_auth',
            new_name='parent_authorization',
        ),
    ]
